<a href="https://colab.research.google.com/github/3b032092/2025_ML_Hws/blob/main/hw6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#第二題

In [1]:
import numpy as np

x1 = np.array([0.1, 0.2, 0.3])
x2 = np.array([0.4, 0.5, 0.6])
x3 = np.array([0.7, 0.8, 0.9])

Wx = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

Wh = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5, 1.6]
])

b = np.array([0.1, 0.1, 0.1, 0.1])

h0 = np.zeros(4)

def rnn_step(x_t, h_prev):
    return np.tanh(np.dot(x_t, Wx) + np.dot(h_prev, Wh) + b)

# 計算 h1, h2, h3
h1 = rnn_step(x1, h0)
h2 = rnn_step(x2, h1)
h3 = rnn_step(x3, h2)

print("h1 =", h1)
print("h2 =", h2)
print("h3 =", h3)


h1 = [0.44624361 0.49298797 0.53704957 0.57836341]
h2 = [0.98540169 0.99280276 0.99645832 0.9982588 ]
h3 = [0.99952208 0.99986638 0.99996264 0.99998956]


#第三題

In [2]:
S3 = np.array([2, 5, 3, 1])

e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)

e = np.array([e1, e2, e3])

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

alpha = softmax(e)
alpha1, alpha2, alpha3 = alpha

c3 = alpha1 * h1 + alpha2 * h2 + alpha3 * h3

print("注意力強度 e =", e)
print("注意力分數 α =", alpha)
print("Context 向量 c3 =", c3)


注意力強度 e = [ 5.54693917 10.92245094 10.99825354]
注意力分數 α = [0.00222166 0.47998967 0.51778867]
Context 向量 c3 = [0.99151525 0.9953498  0.99725217 0.9982221 ]


#第四題

In [4]:
import numpy as np

x1 = np.array([1, 0, 1])
x2 = np.array([0, 1, 1])
x3 = np.array([1, 1, 0])

X = np.array([x1, x2, x3])

W_Q = np.array([[0, 2, 1],
                [1, 0, 3],
                [1, 0, 1]])

W_K = np.array([[1, 1, 0],
                [2, 1, 1],
                [0, 1, 1]])

W_V = np.array([[1, 0, 1],
                [0, 1, 0],
                [1, 1, 0]])

Q = X @ W_Q
K = X @ W_K
V = X @ W_V

print("Q =", Q)
print("K =", K)
print("V =", V)

d_k = K.shape[1]
scores = Q @ K.T / np.sqrt(d_k)

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # prevent overflow
    return e_x / np.sum(e_x, axis=1, keepdims=True)

A = softmax(scores)
attention_output = A @ V

print("Attention weights A =", A)
print("Self-Attention output =", attention_output)


Q = [[1 2 2]
 [2 0 4]
 [1 2 4]]
K = [[1 2 1]
 [2 2 2]
 [3 2 1]]
V = [[2 1 1]
 [1 2 0]
 [1 1 1]]
Attention weights A = [[0.10177799 0.575273   0.32294901]
 [0.02324709 0.74269209 0.23406082]
 [0.04523245 0.81124169 0.14352586]]
Self-Attention output = [[1.10177799 1.575273   0.424727  ]
 [1.02324709 1.74269209 0.25730791]
 [1.04523245 1.81124169 0.18875831]]


##驗證

In [5]:
q1 = x1 @ W_Q
k1 = x1 @ W_K
v1 = x1 @ W_V

print("q1:", q1)
print("Q[0]:", Q[0])
print("驗證 q1 是否等於 Q[0]:", np.allclose(q1, Q[0]))


q1: [1 2 2]
Q[0]: [1 2 2]
驗證 q1 是否等於 Q[0]: True
